NumPy

In [2]:
import numpy as np
import time
import sys

l = range(1000)

In [3]:
print(sys.getsizeof(5)*len(l)) # 28000 bytes per integer in a list of 1000 integers 

28000


In [4]:
a = np.arange(1000)

In [6]:
print(a.size*a.itemsize) # 4000 bytes for 1000 elements of 4 bytes each (int32)

8000


In [8]:
import numpy as np
import time
import sys

SIZE = 1000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# Python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time() - start)*1000)

# Numpy array
start = time.time()
result = a1 + a2
print ("numpy took : " , (time.time() - start)*1000)


python list took:  0.0
numpy took :  0.0


In [9]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Basic Numpy function

In [20]:
a = np.array([5,6,9])
print("Dimension : ", a.ndim)

print(a[0])
print(a[1])
print(a[2])
print()

a = np.array([[1,2],[3,4],[5,6]])
print("Dimension : ",a.ndim) # it will print the number of dimensions

print("Item size : ", a.itemsize) # it will print the size of each item in bytes
print("Data Type  : ", a.dtype) # it will print the data type of the array
print("Size : ", a.size) # it will print the number of items in the array

a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64) # also we can use dtyp = "complex"
print("Data Type  : ", a.dtype) # it will print the data type of the array
print("Size : ", a.size) # it will print the number of items in the array
print(a.shape)

Dimension :  1
5
6
9

Dimension :  2
Item size :  8
Data Type  :  int64
Size :  6
Data Type  :  float64
Size :  6
(3, 2)


In [27]:
np.arange(1,20,3) # it will create an array from 1 to 20 with a step of 3
np.linspace(1,5,10) # it will create an array from 1 to 5 with 10 elements

a = np.array([[1,2],[3,4],[5,6]])
a.reshape(2,3)
a.ravel() # it will convert the array into a single dimension array

array([1, 2, 3, 4, 5, 6])

In [34]:
print(a.min())
print(a.max())
print(a.sum())
print(a)
print(a.sum(axis=0)) # it will print the sum of each column
print(a.sum(axis=1)) # it will print the sum of each row

1
6
21
[[1 2]
 [3 4]
 [5 6]]
[ 9 12]
[ 3  7 11]


In [35]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [36]:
np.std(a)

np.float64(1.707825127659933)

In [39]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [45]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

for row in a:
    print(row)

for cell in a.flat:
    print(cell)

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [52]:
a = np.arange(6).reshape(3,2)
a

b = np.arange(6,12).reshape(3,2)
b

np.vstack((a,b))
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [53]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [54]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [58]:
a = np.arange(12).reshape(3,4)  
a

b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [62]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [63]:
import numpy as np
a = np.arange(12).reshape(3,4)

In [67]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [68]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [71]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [73]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [74]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11
